#
# Module manifest for module 'SPSMonday'
#
# Generated by: jgeron
#
# Generated on: 6/11/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SPSMonday.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-5e6f-7890-abcd-ef1234567890'

# Author of this module
Author = 'Jesse Geron'

# Company or vendor of this module
CompanyName = 'Jesse Geron'

# Copyright statement for this module
Copyright = '(c) Jesse Geron. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module is used to interact with the Monday.com API for retrieving board data, managing Monday.com workflows, and managing board structure including columns.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
#RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(  'Get-MondayBoard',
                        'Get-MondayBoardColumn',
                        'Get-MondayBoardDetail',
                        'Get-MondayBoardItem',
                        'Get-MondayUser',
                        'New-MondayBoardItem',
                        'Set-MondayBoardItem',
                        'Remove-MondayBoardItem',
                        'New-MondayBoardColumn',
                        'Remove-MondayBoardColumn',
                        'Set-MondayBoardColumnTitle',
                        'Set-MondayBoardColumnMetadata',
                        'Invoke-MondayApi',
                        'New-SPSMondayConfiguration',
                        'Set-SPSMondayConfiguration',
                        'Get-SPSMondayConfiguration'
                     )

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('Get-MondayItem')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Monday', 'API', 'ProjectManagement', 'Workflow')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://developer.monday.com/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Version 1.1.0: Added column management functions - New-MondayBoardColumn, Remove-MondayBoardColumn, Set-MondayBoardColumnTitle, and Set-MondayBoardColumnMetadata for complete board structure management'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}








































