name: Build and Deploy SPSMonday Module

on:
  push:
    branches: [ main, master ]
    paths:
      - 'SPSMonday/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'SPSMonday/**'
  release:
    types: [published]

env:
  MODULE_NAME: SPSMonday

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4    
    - name: Setup PowerShell
      shell: pwsh
      run: |
        Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"
        Write-Host "OS: $($PSVersionTable.OS)"
    
    - name: Install required modules
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck
        Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck
    
    - name: Test module manifest
      shell: pwsh
      run: |
        Write-Host "Testing module manifest..." -ForegroundColor Yellow
        # Temporarily replace version placeholder for testing
        $manifestPath = ".\SPSMonday\SPSMonday.psd1"
        $manifestContent = Get-Content -Path $manifestPath -Raw
        $testContent = $manifestContent -replace '<ModuleVersion>', '1.0.0'
        $testContent | Set-Content -Path ".\SPSMonday\SPSMonday.test.psd1"
        
        $manifest = Test-ModuleManifest -Path ".\SPSMonday\SPSMonday.test.psd1" -ErrorAction Stop
        Write-Host "✓ Manifest is valid" -ForegroundColor Green
        Write-Host "  Module: $($manifest.Name)" -ForegroundColor Gray
        Write-Host "  Version: $($manifest.Version)" -ForegroundColor Gray
        Write-Host "  Functions: $($manifest.ExportedFunctions.Keys.Count)" -ForegroundColor Gray
        
        # Clean up test file
        Remove-Item ".\SPSMonday\SPSMonday.test.psd1" -Force
    
    - name: Run PSScriptAnalyzer
      shell: pwsh
      run: |
        Write-Host "Running PSScriptAnalyzer..." -ForegroundColor Yellow
        $results = Invoke-ScriptAnalyzer -Path ".\SPSMonday" -Recurse -Settings PSGallery
        if ($results) {
          Write-Host "PSScriptAnalyzer found issues:" -ForegroundColor Red
          $results | Format-Table -AutoSize
          exit 1
        } else {
          Write-Host "✓ PSScriptAnalyzer passed" -ForegroundColor Green
        }
    
    - name: Test module import
      shell: pwsh
      run: |
        Write-Host "Testing module import..." -ForegroundColor Yellow
        try {
          Import-Module .\SPSMonday\SPSMonday.psd1 -Force -ErrorAction Stop
          $functions = Get-Command -Module SPSMonday -CommandType Function
          Write-Host "✓ Module imported successfully" -ForegroundColor Green
          Write-Host "  Functions exported: $($functions.Count)" -ForegroundColor Gray
          Remove-Module SPSMonday -Force
        } catch {
          Write-Error "Module import failed: $_"
          exit 1
        }

  build:
    needs: test
    runs-on: windows-latest
    if: github.event_name != 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Determine version
      id: version
      shell: pwsh
      run: |
        if ($env:GITHUB_EVENT_NAME -eq 'release') {
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        } else {
          # Get version from manifest and append build number
          $manifest = Import-PowerShellDataFile -Path ".\SPSMonday\SPSMonday.psd1"
          $baseVersion = $manifest.ModuleVersion -replace '<ModuleVersion>', '1.0.0'
          $version = "$baseVersion.$env:GITHUB_RUN_NUMBER"
        }
        
        Write-Host "Build Version: $version" -ForegroundColor Green
        echo "BUILD_VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "buildVer=$version" >> $env:GITHUB_ENV
    
    - name: Build module
      shell: pwsh
      run: |
        Write-Host "Building module with version: $env:buildVer" -ForegroundColor Green
        .\build.ps1    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SPSMonday-Module-${{ steps.version.outputs.BUILD_VERSION }}
        path: SPSMonday/
        retention-days: 30

  deploy:
    needs: [test, build]
    runs-on: windows-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: SPSMonday-Module-*
        merge-multiple: true
        path: SPSMonday/
    
    - name: Determine version
      id: version
      shell: pwsh
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        Write-Host "Deploy Version: $version" -ForegroundColor Green
        echo "DEPLOY_VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "buildVer=$version" >> $env:GITHUB_ENV
    
    - name: Build module for deployment
      shell: pwsh
      run: |
        Write-Host "Building module for deployment with version: $env:buildVer" -ForegroundColor Green
        .\build.ps1
    
    - name: Deploy to PowerShell Gallery
      shell: pwsh
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        if ([string]::IsNullOrWhiteSpace($env:NUGET_API_KEY)) {
          Write-Error "NUGET_API_KEY secret is not set"
          exit 1
        }
        
        Write-Host "Deploying to PowerShell Gallery..." -ForegroundColor Green
        .\deploy.ps1 -NuGetApiKey $env:NUGET_API_KEY -BuildVersion $env:buildVer
    
    - name: Create deployment summary
      shell: pwsh
      run: |
        $moduleName = "SPSMonday"
        $version = $env:buildVer
        
        Write-Host "## Deployment Summary" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "- **Module**: $moduleName" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "- **Version**: $version" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "- **Repository**: PowerShell Gallery" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "- **Status**: ✅ Deployed Successfully" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "- **Install Command**: \`Install-Module -Name $moduleName\`" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "- **Gallery Link**: [View on PowerShell Gallery](https://www.powershellgallery.com/packages/$moduleName/$version)" >> $env:GITHUB_STEP_SUMMARY
